### PR TITLE
mate-colorsel: avoid deprecated 'gtk_widget_modify_bg'

### PR DESCRIPTION
**Pull request by sc0w**
The expected: the same colors here:

### CODE REVIEW

**Comment by raveit65** [comment]
Do you really want to fix deprecation here?
In the end all this code needs to be dropped for Gtk+4 because there is no replacement for deprecated GtkHSV.
https://developer.gnome.org/gtk3/stable/GtkHSV.html
Sadly, the UI with the color-cycle doesn't have any future.
Your decision....i only wanted inform you.

**Comment by sc0w** [comment]
@raveit65 ok, I noticed it now

I like to fix deprecations everywhere, I think it is early to thinking in gtk 4.

**Comment by sc0w** [comment]
@lukefromdc  Is not easy to fork GtkStatusIcon, believe me, it has a loooot of mooore deprecated code internally.

**Comment by sc0w** [comment]
I think GtkHSV can be forked to mate

**Pull request merged**
