### PR TITLE
Fix compilation warning

### PR DESCRIPTION
**Pull request by zhuyaliang**
I fixed some compilation warnings  replaced some outdated API.
Next I'll use ```gdk_raba``` replaces ```gdk_color```

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
We get a new runtime warning with this:

`(mate-color-select:144364): Gtk-CRITICAL **: 13:47:22.095: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed`

Note that (as in master) the mate-color-select comes up with white (FFFFFF) as the default color, so don't be confused by the color value and right half of the color strip not changing as the triangulalr hue widget is rotated until the saturation circle is moved off of pure white. The runtime warning has nothing to do with that, as confirmed by testing master as well

**Comment by zhuyaliang** [comment]
@lukefromdc Repair the warning generated at run time, please test again

**Review by lukefromdc — APPROVED** [review]
The runtime warning is gone, the built mate-color-select binary works fine

**Review by vkareh — APPROVED** [review]
LGTM

**Pull request merged**
