### PR TITLE
build: remove mate-about.h on distclean target instead of clean

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
But than `make clean` doesn't remove `mate-about.h`.
So why you want to move it to `distclean`?

**Comment by rbuj** [comment]
before (master): `make clean` removes `mate-about.h`
```shell
$ make distclean; ./autogen.sh --prefix=/usr && make && make clean V=1
<cut>
Making clean in mate-about
make[1]: Entering directory '/home/robert/mate-desktop/mate-about'
 rm -f mate-about
test -z "mate-about.desktop mate-about mate-version.xml mate-about.h" || rm -f mate-about.desktop mate-about mate-version.xml mate-about.h
<cut>
```
after (PR): `make clean` doesn't remove `mate-about.h`
```shell
$ make distclean; ./autogen.sh --prefix=/usr && make && make clean V=1
<cut>
Making clean in mate-about
make[1]: Entering directory '/home/robert/mate-desktop/mate-about'
 rm -f mate-about
test -z "mate-about.desktop mate-about mate-version.xml" || rm -f mate-about.desktop mate-about mate-version.xml
<cut>
```

**Comment by raveit65** [comment]
I know the different between clean and distclean. But again, why you want to move it to `distclean`?
What is the advantage?

**Comment by rbuj** [comment]
The advantage is that the mate-about.h file should be only generated in the configuration step, since it's part of AC_CONFIG_FILES (configure.ac).

**Comment by rbuj** [comment]
$(version_DATA) should be also removed on distclean target instead of clean, i.e. it should be part of DISTCLEANFILES instead of CLEANFILES.

**Pull request merged**
