### PR TITLE
Lose the color-picker and always use hardcoded crosshair cursor

### PR DESCRIPTION
**Pull request by nokangaroo**
Not all cursor themes have a color-picker cursor. This commit uses a hardcoded crosshair cursor for mate-colorsel.c. The existing fallback cursor looks broken

### CODE REVIEW

**Comment by raveit65** [comment]
whow, first commit changes about 300 files.
https://github.com/mate-desktop/mate-desktop/pull/263/commits/44241856246c0064b893259a034afc2d2b3c00c0

**Comment by monsta** [comment]
I don't think it's a good idea to commit all the generated files, including .o files :slightly_smiling_face:

**Comment by nokangaroo** [comment]
Where did the .o files come from? My local branch seems to be clean.

**Comment by monsta** [comment]
> I ran git clean -f 

According to git manual, it only cleans files that aren't under version control, so it's too late to run that command now :slightly_smiling_face: 

I'd just reset the branch to two commits earlier (current git master here), then re-apply the fixes and force-push the branch.

**Pull request closed without merging**
