### PR TITLE
mate-dmi: add new api to get dmi info

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by lukefromdc** [comment]
What is dmi info? This is the first I've seen that term

**Review by zhuyaliang — COMMENTED** [review]
Systemd provides the same interface functionality

**Comment by zhuyaliang** [comment]
2023-10-06 08-41-32 创建的截图
We can directly use the ```gdbus``` interface provided by ```systemd```, otherwise it will increase our maintenance costs

**Comment by lukefromdc** [comment]
How would I test this?

**Comment by yetist** [comment]
> We can directly use the ```gdbus``` interface provided by ```systemd```, otherwise it will increase our maintenance costs

Good, thanks.

**Comment by yetist** [comment]
> How would I test this?

you can run the test-dmi command to see the output, but I think we dont need this PR now.

**Pull request closed without merging**
