### PR TITLE
switch mate-about to GtkAboutDialog and drop MateAboutDialog

### PR DESCRIPTION
**Pull request by monsta**
Please test and tell what you think about the height of the credits window. In my opinion, it's too small for the huge amount of credits we have in mate-about app. But if it's ok with you guys, I think we can merge it.

### CODE REVIEW

**Comment by raveit65** [comment]
You are kidding :-)
```
[rave@mother mate-desktop]$ LANG=C
[rave@mother mate-desktop]$ git rebase master
First, rewinding head to replay your work on top of it...
Applying: mate-about: switch to GtkAboutDialog
Applying: mate-about: remove remains of libunique references
Applying: drop MateAboutDialog
Using index info to reconstruct a base tree...
M	libmate-desktop/mate-aboutdialog.c
Falling back to patching base and 3-way merge...
Removing libmate-desktop/mate-aboutdialog.h
CONFLICT (modify/delete): libmate-desktop/mate-aboutdialog.c deleted in drop MateAboutDialog and modified in HEAD. Version HEAD of libmate-desktop/mate-aboutdialog.c left in tree.
error: Failed to merge in the changes.
Patch failed at 0003 drop MateAboutDialog
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

**Comment by raveit65** [comment]
For me this scrolledwindow with the credit credit list is OK.
mate-about


But it's possible to set a height-request for the whole GtkAbouDialog, ie 600. ;-)
mate-about-with-height-rquest
And you can set the window resizable if you want.

At least this list needs to sorted to reflect more reality.

**Comment by monsta** [comment]
Hmm I thought I already rebased it and solved that conflict in the process... Ok, here goes another rebase. :slightly_smiling_face:

**Comment by monsta** [comment]
I didn't know GtkAboutDialog can be made resizable BTW. I think all our apps use non-resizable one...

**Comment by raveit65** [comment]
https://developer.gnome.org/gtk3/unstable/GtkWidget.html#gtk-widget-set-size-request
https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-resizable
The default is **Windows are user resizable by default**
So is this setup somewhere?

**Comment by raveit65** [comment]
At least i can change those values with gtk3-inspector, so it should be work in code too.

**Comment by raveit65** [comment]
I am using this for f27 beta, don't know for what you waiting for.....

**Comment by monsta** [comment]
Ok, I'll merge it as is for now, it's been a long time indeed.

**Pull request merged**
