### PR TITLE
Add test code for mate-languages

### PR DESCRIPTION
**Pull request by yetist**
Add test code for mate-languages.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Can this be tested on a system with all but 2 locales purged or now?

**Comment by raveit65** [comment]
After installation an session restart.
```
[rave@mother libmate-desktop]$ ./test-languages

(process:4390): MateDesktop-WARNING **: 17:57:31.674: Could not read list of available locales from libc, guessing possible locales from available translations, but list may be incomplete!
[rave@mother libmate-desktop]$ locale -a
aa_DJ
aa_DJ.iso88591
aa_DJ.utf8
aa_ER
aa_ER@saaho
aa_ER.utf8
aa_ER.utf8@saaho
aa_ET
aa_ET.utf8
af_ZA
af_ZA.iso88591

<cut>

yuw_PG
yuw_PG.utf8
zh_CN
zh_CN.gb18030
zh_CN.gb2312
zh_CN.gbk
zh_CN.utf8
zh_HK
zh_HK.big5hkscs
zh_HK.utf8
zh_SG
zh_SG.gb2312
zh_SG.gbk
zh_SG.utf8
zh_TW
zh_TW.big5
zh_TW.euctw
zh_TW.utf8
zu_ZA
zu_ZA.iso88591
zu_ZA.utf8
```
Do i miss something?

**Comment by yetist** [comment]
Now rebase on the master branch.

@raveit65 

Please use the follow code to see the locale directory, that should be like `/usr/local/share/locale/<LANG>/LC_MESSAGES`, if not, maybe you need this PR: #386

```
--- a/libmate-desktop/mate-languages.c
+++ b/libmate-desktop/mate-languages.c
@@ -344,6 +344,7 @@ mate_language_has_translations (const char *code)
         g_autofree char *path = NULL;
 
         path = g_build_filename (MATELOCALEDIR, code, "LC_MESSAGES", NULL);
+        g_print("%s\n", path);
 
         has_translations = FALSE;
         dir = g_dir_open (path, 0, NULL);
```

**Comment by raveit65** [comment]
Test build was from master + PR which have https://github.com/mate-desktop/mate-desktop/pull/386

**Comment by raveit65** [comment]
Ok, with this code line i see `/usr/local/share/locale/<LANG>/LC_MESSAGES`
But only if there are empty locale dirs.
I would expect that the testcode checks for normal `/usr/share/locale/<LANG>/LC_MESSAGES` dirs.

**Comment by yetist** [comment]
@raveit65 

This path comes from `MATELOCALEDIR`, which is defined in Makefile.am, according to `localedir`.
```
    -DMATELOCALEDIR=\""$(localedir)\""          \
```
So, your advice is that I need a hard-coded path for `/usr/share/locale` ?

**Comment by raveit65** [comment]
I think a normal installation of locale by a package-manager of a distro is /usr/share/locale.
Does i make sense to test a dir which isn't use by most people?
If it isn't possible to check for both dirs than i prefer /usr/share/locale, ihmo.

**Comment by yetist** [comment]
> If it isn't possible to check for both dirs than i prefer /usr/share/locale, ihmo.
OK, let's check the both dirs.

**Comment by raveit65** [comment]
@lukefromdc 
You like to check test-code with one locale or shout i merge it?

**Comment by lukefromdc** [comment]
I never saw that because I have been overwhelmed lately with the compiz work. No problem with the merge

**Pull request merged**
