### PR TITLE
Thumbnail improvements.

### PR DESCRIPTION
**Pull request by raveit65**
Please test and review.

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
> I had to press Ctrl+C for closing the preview window.

Or closing it with window-manger buttons. But is this a bug?

> It only accepts one file path as command line argument.

I am sure this can be improved, I back ported only the initial commit for the test program, to avoid that the PR becomes to huge.
Again, is this a bug or do you want improve it, which can be done later ?

**Comment by rbuj** [comment]
@raveit65 
```patch
diff --git a/libmate-desktop/test-desktop-thumbnail.c b/libmate-desktop/test-desktop-thumbnail.c
index eb17186..5aeb325 100644
--- a/libmate-desktop/test-desktop-thumbnail.c
+++ b/libmate-desktop/test-desktop-thumbnail.c
@@ -50,7 +50,9 @@ int main (int argc, char **argv)
     }
 
     window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
+    g_signal_connect (window, "destroy", G_CALLBACK (gtk_main_quit), NULL);
     image = gtk_image_new_from_pixbuf (pixbuf);
+    g_object_unref (pixbuf);
     gtk_container_add (GTK_CONTAINER (window), image);
     gtk_widget_show_all (window);
 
```

**Comment by raveit65** [comment]
@rbuj 
I know you don't like to speak but i don't understand you.
Can you you use regular sentences with words please?

**Comment by rbuj** [comment]
For the execution of the test: ./test-desktop-thumbnail FILENAME:

The window cannot be destroyed if no signal is connected, there are also memory leaks.
```patch
diff --git a/libmate-desktop/test-desktop-thumbnail.c b/libmate-desktop/test-desktop-thumbnail.c
index eb17186..c37428b 100644
--- a/libmate-desktop/test-desktop-thumbnail.c
+++ b/libmate-desktop/test-desktop-thumbnail.c
@@ -43,6 +43,7 @@ int main (int argc, char **argv)
     factory = mate_desktop_thumbnail_factory_new (MATE_DESKTOP_THUMBNAIL_SIZE_LARGE);
     pixbuf = mate_desktop_thumbnail_factory_generate_thumbnail (factory, argv[1], content_type);
     g_free (content_type);
+    g_object_unref (factory);
 
     if (pixbuf == NULL) {
         g_warning ("mate_desktop_thumbnail_factory_generate_thumbnail() failed to generate a thumbnail for %s", argv[1]);
@@ -50,7 +51,9 @@ int main (int argc, char **argv)
     }
 
     window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
+    g_signal_connect (window, "destroy", G_CALLBACK (gtk_main_quit), NULL);
     image = gtk_image_new_from_pixbuf (pixbuf);
+    g_object_unref (pixbuf);
     gtk_container_add (GTK_CONTAINER (window), image);
     gtk_widget_show_all (window);
 
```

**Comment by raveit65** [comment]
@rbuj 
Thanks for the fix. PR is updated.

**Pull request merged**
