### PR TITLE
Fix cursor

### PR DESCRIPTION
**Pull request by nokangaroo**
The default fallback cursor in mate-colorsel.c is broken; it looks very weird. I added 2 commits, one to change the fallback cursor using a color-picker cursor created with gimp, and one to use a hardcoded crosshair cursor by default

### CODE REVIEW

**Comment by nokangaroo** [comment]
Hope this works now

**Comment by raveit65** [comment]
I added the color-picker image to our cursor theme to all branches,  shipped by mate-themes.
https://github.com/mate-desktop/mate-themes/commit/6a72c195f8e365ac269d7af7d37ce24234bdf59b
So i would like to see not to drop the usage to load it from cursor themes.
Updating the fallback pixbuf is fine.
We release mate-themes very often usually, so you would see it fast in your distro.

**Comment by raveit65** [comment]
@nokangaroo 
I'd like to merge the pixbuff fallback stuff.
Can  you update PR please?

**Comment by raveit65** [comment]
Ok, i merged the first commit https://github.com/mate-desktop/mate-desktop/commit/7496cb0012b79aa4960b1bf9bfc56429d2e62226
Thank you.

**Pull request closed without merging**
