### PR TITLE
schemas: Define schema for a default messenger

### PR DESCRIPTION
**Pull request by rbuj**
Defines a schema that allows users to specify a default instant messaging application.
Default initialized to 'pidgin'.

### CODE REVIEW

**Comment by vkareh** [comment]
This works fine, pending an approval on https://github.com/mate-desktop/mate-control-center/pull/457, but should we default it to just empty, since MATE doesn't specifically endorse any specific IM client?

**Comment by rbuj** [comment]
Similar case with Web Browser, by default is set to 'mozilla'. It should be updated to ['firefox'](https://wiki.debian.org/Firefox).
https://github.com/mate-desktop/mate-desktop/blob/d53d2be25eded44f81c126c9d904d21774f7ee42/schemas/org.mate.applications-browser.gschema.xml#L4

**Comment by lukefromdc** [comment]
I think that will need to default to empty for that reason.

**Comment by rbuj** [comment]
@vkareh @lukefromdc done

**Comment by raveit65** [comment]
I will reword commit body to match latest default.

**Comment by lukefromdc** [comment]
It would seem to me we should now increment version to 1.23.1 since we've added a new schema that a mate-control-center change will depend on

**Comment by raveit65** [comment]
Ok, i will make a new mate-desktop release.

**Comment by raveit65** [comment]
I just bumped version to 1.23.1 https://github.com/mate-desktop/mate-desktop/commit/f3a7cc35331b06c69a8c8c07da372cf73bbc5d13

**Pull request merged**
