### PR TITLE
build: use localedir instead of DATADIRNAME

### PR DESCRIPTION
**Pull request by hanetzer**
Fixes https://github.com/zhuyaliang/user-admin/issues/21

Signed-off-by: Marty E. Plummer <hanetzer@startmail.com>

### CODE REVIEW

**Comment by raveit65** [comment]
You did it !
Bildschirmfoto zu 2019-05-25 17-44-06

**Comment by hanetzer** [comment]
Yeah, this was my bad. Apparently DATADIRNAME is a legacy variable which got lost
in the move from glib-gettext. Wasn't mentioned in the migrating doc I referenced from
gnome. Maybe I'll bug them about it and get the page updated.
https://wiki.gnome.org/MigratingFromIntltoolToGettext

**Comment by rbuj** [comment]
LGTM.

Can't select the correct locale for Catalan as they are two locales with the same name "Català (Espanya)". Similar issue with langtable https://bugzilla.redhat.com/show_bug.cgi?id=1698984

Captura de pantalla a 2019-05-25 18-35-32

**Comment by hanetzer** [comment]
@rbuj Yeah; this may be an existing issue though. Someone on older mate-desktop give it a go?

**Pull request merged**
