### PR TITLE
Remove useless mate_color_button apis

### PR DESCRIPTION
**Pull request by zhuyaliang**
The ```mate_color_button``` has not been called by any code. ```GtkColorChooser``` has been used instead of ```MateColorButton```  In order to reduce maintenance costs, we should streamline the code and remove some unused code

### CODE REVIEW

**Comment by raveit65** [comment]
It think last usage was with mate-color-chooser but it was converted to gtk-color-chooser some years ago.
https://github.com/mate-desktop/mate-panel/pull/464

**Comment by zhuyaliang** [comment]
The ```mate_color button``` is no longer in use

**Comment by raveit65** [comment]
`make distcheck` runs fine.
For some reason `meson dist` works only with `--allow-dirty` flag.
No idea, it that is a problem.
I noticed that with another repo too.

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by zhuyaliang** [comment]
@raveit65 Can I merge the code? My next PR to replace expired functions and fix compilation warnings will be based on this
@lukefromdc @cwendling @yetist Please help review the code

**Review by yetist — APPROVED** [review]
LGTM

**Review by lukefromdc — APPROVED** [review]
Both autotools and meson builds finished fine, no surprises on installing the autotools build but none expected as this just removes the unused colorbutton. EDIT: this removes the button API but we keep the stanalone mate-color-select binary

**Comment by raveit65** [comment]
@zhuyaliang @lukefromdc 
During testing new PRs i noticed that `mate-desktop.abi` isn't in EXTRA_DIST or released Tarballs.
Do we don't need this file for runtime?
Is it only for documentation?

**Comment by raveit65** [comment]
Maybe it is useful for users when we ship those file with tarballs?
I can do that.

**Pull request merged**
