### PR TITLE
schemas: Define schema for a default calculator

### PR DESCRIPTION
**Pull request by zhangxianwei8**
• Defines a schema that allows users to specify a default calculator application.
• Default initialized to 'galculator'.
• By itself, this PR does not change much. However, it allows for other relevant PRs to act on the existence of this schema.
• Will open PR at https://github.com/mate-desktop/mate-control-center to open a PR to control the schema
• Will open PR at https://github.com/mate-desktop/mate-settings-daemon to update https://github.com/mate-desktop/mate-settings-daemon/blob/master/plugins/media-keys/msd-media-keys-manager.c to honor the schema as opposed to the following behavior:
1. Execute 'galculator', if available.
2. If 'galculator' is not available, execute 'mate-calc', if available.
3. If 'mate-calc' is not available, execute 'gnome-calculator', if available.
4. If 'gnome-calculator' is not available, silently do nothing.

### CODE REVIEW

**Comment by lukefromdc** [comment]
https://github.com/zhangxianwei8/mate-desktop/pull/1
Is a PR to this PR to fix the build and install the schema

**Comment by zhangxianwei8** [comment]
Thank you. Already updated. @lukefromdc

**Comment by lukefromdc** [comment]
Thanks, secondary PR closed

**Comment by raveit65** [comment]
Mate-calc should be the default.

**Comment by zhangxianwei8** [comment]
OK. Updated!

**Comment by lukefromdc** [comment]
The change of default is confirmed to work on a test session where the choice of calculator has never been configured but mate-calc is installed. The whole set of PR's now works very well

**Pull request merged**
