### PR TITLE
MateHSV implementation (GtkHSV fork)

### PR DESCRIPTION
**Pull request by sc0w**
Note: we have a lot of lines here, please don't merge to the 1.22 release

### CODE REVIEW

**Comment by yetist** [comment]
Please rebase on master, all check will be passed.

**Comment by monsta** [comment]
@raveit65: what if we port `mate-color-select` to GTK+3 version of color selection widget (instead of the current color wheel)? It's our only app that uses the old widget.

**Comment by lukefromdc** [comment]
The color wheel but NOT the palette grid is used by caja's "backgrounds and emblems" dialog for adding a new background color for folders (not the desktop). We could port both of those to GTK3's color selection widget as everything else already has been, or at the risk of higher maintainance port all our other color selectors back to the color wheel.

Our version is easier to use and in my opinion just plain a better version, but unless we plan to use it more widely we should probably drop it as it is unused code to most users.

**Comment by raveit65** [comment]
For me the new color selection from gtk+ isn't so bad and i don't think it is more complicated to use than our traditional color cycle.
I like that i can use transparent rgba colors definition.

**Comment by monsta** [comment]
Well, for example, mate-system-monitor already uses the new color selector (for CPU colors and stuff).

**Comment by sc0w** [comment]
@monsta  with the "new color selector" the user can click a color anywhere on the screen to select that color?

**Comment by monsta** [comment]
Good question... I didn't see that there.

**Comment by raveit65** [comment]
Beside that the color-cycle is replaced with something new, our GUI has 2 functions which aren't anymore in the new gtk3 gui.
bildschirmfoto zu 2019-02-13 21-38-57
1. The color picker is gone.
2. You can't type rgb values and convert them to hex values.

That the new gtk3 GUI use rgba colors is one advantage.

So , i think it isn't worse to fork GtkHSV.

**Pull request merged**
