### PR TITLE
GEN png icons from hicolor_apps_scalable_mate.svg

### PR DESCRIPTION
**Pull request by rbuj**
Update icon cache and avoid conflict with mate theme:
```python
import gtk
screen = gtk.gdk.screen_get_default()
icon_theme = gtk.icon_theme_get_for_screen(screen)
print icon_theme.lookup_icon("mate-desktop", 16, 0).get_filename()
print icon_theme.lookup_icon("mate-desktop", 22, 0).get_filename()
print icon_theme.lookup_icon("mate-desktop", 24, 0).get_filename()
print icon_theme.lookup_icon("mate-desktop", 32, 0).get_filename()
print icon_theme.lookup_icon("mate-desktop", 48, 0).get_filename()
print icon_theme.lookup_icon("mate-desktop", 128, 0).get_filename()
print icon_theme.lookup_icon("mate-desktop", 256, 0).get_filename()
print icon_theme.lookup_icon("mate", 16, 0).get_filename()
print icon_theme.lookup_icon("mate", 22, 0).get_filename()
print icon_theme.lookup_icon("mate", 24, 0).get_filename()
print icon_theme.lookup_icon("mate", 32, 0).get_filename()
print icon_theme.lookup_icon("mate", 48, 0).get_filename()
print icon_theme.lookup_icon("mate", 128, 0).get_filename()
print icon_theme.lookup_icon("mate", 256, 0).get_filename()
print icon_theme.lookup_icon("mate", 1000, 0).get_filename()
```
```sh
/usr/share/icons/hicolor/16x16/apps/mate-desktop.png
/usr/share/icons/hicolor/22x22/apps/mate-desktop.png
/usr/share/icons/hicolor/24x24/apps/mate-desktop.png
/usr/share/icons/hicolor/32x32/apps/mate-desktop.png
/usr/share/icons/hicolor/48x48/apps/mate-desktop.png
/usr/share/icons/hicolor/128x128/apps/mate-desktop.png
/usr/share/icons/hicolor/scalable/apps/mate-desktop.svg
/usr/share/icons/mate/16x16/apps/mate.png
/usr/share/icons/mate/22x22/apps/mate.png
/usr/share/icons/mate/24x24/apps/mate.png
/usr/share/icons/mate/32x32/apps/mate.png
/usr/share/icons/mate/48x48/apps/mate.png
/usr/share/icons/mate/scalable/apps/mate.svg
/usr/share/icons/mate/scalable/apps/mate.svg
/usr/share/icons/mate/scalable/apps/mate.svg
```

### CODE REVIEW

**Comment by lukefromdc** [comment]
Will this cause any problems for HiDPI scaling?

**Comment by rbuj** [comment]
The current png files they don't have the same dpi:
```sh
find . -name "*.png" -exec identify -format "%w x %h %x x %y\n" {} \; | sort -n
16 x 16 11.810000000000000497 x 11.810000000000000497
22 x 22 16.239999999999998437 x 16.239999999999998437
24 x 24 17.719999999999998863 x 17.719999999999998863
32 x 32 23.620000000000000995 x 23.620000000000000995
48 x 48 35.429999999999999716 x 35.429999999999999716
256 x 256 188.97999999999998977 x 188.97999999999998977
```
New png files:
```sh
find . -name "*.png" -exec identify -format "%w x %h %x x %y\n" {} \; | sort -n
16 x 16 72 x 72
22 x 22 72 x 72
24 x 24 72 x 72
32 x 32 72 x 72
48 x 48 72 x 72
256 x 256 72 x 72
```
I think that the old files they were exported using inkscape:
```sh
inkscape -f=hicolor_apps_scalable_mate.svg -w=16 -h=16 -z -e=hicolor_apps_16x16_mate.png
inkscape -f=hicolor_apps_scalable_mate.svg -w=22 -h=22 -z -e=hicolor_apps_22x22_mate.png
inkscape -f=hicolor_apps_scalable_mate.svg -w=24 -h=24 -z -e=hicolor_apps_24x24_mate.png
inkscape -f=hicolor_apps_scalable_mate.svg -w=32 -h=32 -z -e=hicolor_apps_32x32_mate.png
inkscape -f=hicolor_apps_scalable_mate.svg -w=48 -h=48 -z -e=hicolor_apps_48x48_mate.png
inkscape -f=hicolor_apps_scalable_mate.svg -w=256 -h=256 -z -e=hicolor_apps_256x256_mate.png
find . -name "*.png" -exec identify -format "%w x %h %x x %y\n" {} \; | sort -n
16 x 16 12.599999999999999645 x 12.599999999999999645
22 x 22 17.320000000000000284 x 17.320000000000000284
24 x 24 18.899999999999998579 x 18.899999999999998579
32 x 32 25.199999999999999289 x 25.199999999999999289
48 x 48 37.799999999999997158 x 37.799999999999997158
256 x 256 201.56999999999999318 x 201.56999999999999318
```

**Comment by sc0w** [comment]
the build fails here, it seems needs to add **librsvg2-bin** as dependency

```
configure:13322: error: could not locate rsvg-convert

configure: error: could not locate rsvg-convert
```

**Comment by rbuj** [comment]
GTK+ Inspector test: window scaling x3
```
gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true
LANG=C GTK_DEBUG=interactive mate-about
```
HiDPI

**Comment by rbuj** [comment]
@sc0w 
Yes, the first PR failed. I added the dependencies in travis configuration.
Next, I added the configure error for breaking the run if it didn't find rsvg-convert on system.

@lukefromdc 
I couldn't test it because the icon cache was not updated.
```
./autogen.sh --prefix=/usr && make && sudo make install
```
edit/test loop: edit icons/Makefile.am / run test:

```
cd icons
rm *.png
make
sudo make install-icons
```
Then, I found that the mate icon name, it was already present in icon cache:
```sh
$ rpm -qf /usr/share/icons/mate/16x16/apps/mate.png
mate-icon-theme-1.22.0-1.fc31.noarch
```
For that reason I changed the icon name to mate-desktop, and force the icon cache update by running gtk-update-icon-cache

**Comment by lukefromdc** [comment]
What package offers rsvg-convert in Debian? I could not find a package by that name in Synaptic.  Nice looking screenshot BTW with hidpi, looks like we should be OK on that front.

**Comment by sc0w** [comment]
@lukefromdc see my previous comment

you need **librsvg2-bin**

I think the PR needs to add it as dependency in `configure.ac`

**Comment by raveit65** [comment]
Or for rpm-based distros.
```
[root@mother rave]# dnf provides *rsvg-convert
librsvg2-tools-2.45.5-3.fc30.x86_64 : Extra tools for librsvg
Repo        : fedora
Matched from:
Other       : *rsvg-convert
```

**Comment by raveit65** [comment]
This is new and shouldn't happen!
```
RPM build errors:
error: Installed (but unpackaged) file(s) found:
   /usr/share/icons/hicolor/icon-theme.cache
```
Why creating a cache file and is this really needed?
I don't get why the icons should re-created from tarball with every build?
Why not create them one time in github repo and ship the result with a new tarball to the world?

**Comment by rbuj** [comment]
> This is new and shouldn't happen!
> 
> ```
> RPM build errors:
> error: Installed (but unpackaged) file(s) found:
>    /usr/share/icons/hicolor/icon-theme.cache
> ```

Icon cache update is a [post-installation task](https://www.gnu.org/software/automake/manual/html_node/Extending-Installation.html).

**Comment by rbuj** [comment]
> Why creating a cache file and is this really needed?

GTK+ can use the cache files created by gtk-update-icon-cache to avoid a lot of system call and disk seek overhead when the application starts. Since the format of the cache files allows them to be mmaped shared between multiple applications, the overall memory consumption is reduced as well.
[REF](https://developer.gnome.org/gtk3/stable/gtk-update-icon-cache.html)

**Comment by raveit65** [comment]
> Icon cache update is a post-installation task.

True, but i was never to forced to delete this file in my rpm.
Or in any other package which i maintain for fedora.
Why re-creating an icon-set during installation?

**Comment by raveit65** [comment]
> GTK+ can use the cache files created by gtk-update-icon-cache to avoid a lot of system call and disk seek overhead when the application starts. Since the format of the cache files allows them to be mmaped shared between multiple applications, the overall memory consumption is reduced as well.

But this will done by gtk-icon-cache during installation of every package itself.
This shouldn't be done by a package itself.

**Comment by raveit65** [comment]
Don't understand me wrong.
I am not against to improve the quality of this icon-set.
But this should be done as a one shot in repo, and not every time during installation.

**Comment by rbuj** [comment]
> True, but i was never to be forced to delete this file in my rpm.
> Or in any other package which i maintain for fedora.
> Why re-creating an icon-set during installation?

It should work now, I used the [mate-utils code](https://github.com/mate-desktop/mate-utils/blob/910cca04f74645ddbb3dd6e0d70703a1eeb360ef/baobab/pixmaps/24x24/Makefile.am#L18-L29).

**Comment by rbuj** [comment]
> Don't understand me wrong.
> I am not against to improve the quality of this icon-set.
> But this should be done as a one shot in repo, and not every time during installation.

WIP

**Comment by rbuj** [comment]
- PNG icons are created if they are not present in icon folder.
- To remove PNG icons:
`cd icons; make clean-png-icons`

**Comment by raveit65** [comment]
Thanks, that fixes the problem.

**Comment by lukefromdc** [comment]
My debian package made from this installed just fine, didn't conflict with the existing mate-themes package. Worried about that with the comment "avoid conflict with mate theme" in the last commit.

**Comment by monsta** [comment]
Is `rsvg-convert` tool needed during normal build?

**Comment by sc0w** [comment]
@rbuj @monsta please see https://github.com/mate-desktop/mate-desktop/pull/398

**Comment by raveit65** [comment]
Can someone explain me why having `rsvg-convert` as build dependency is a problem here?
And why you want have an ugly blurred icon?
The icon looks much better on HIDPI monitors if `rsvg-convert` is used.

**Pull request merged**
